server:
  port: 5000

spring:
  profiles:
    default: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://awseb-e-2i2yqpaekr-stack-awsebrdsdatabase-yjwqd5ap0ugz.c9huyxklljow.ap-northeast-2.rds.amazonaws.com:3306/luckyseven
    username: admin
    password: rejin0421
    redis:
      host: luckyseven-redis.l6eajq.ng.0001.apn2.cache.amazonaws.com
      port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 46ec58d196bd0e72f56e34641ceec564
            redirect-uri: http://luckyseven-env.ap-northeast-2.elasticbeanstalk.com/auth/kakao
            client-authentication-method: POST
            client-secret: dHp9KmlsjhGhVpE6mFA8jXfsYF1HRzTV
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - birthday
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

cloud:
  aws:
    s3:
      bucket: luckyseven-bucket
    credentials:
      access-key: AKIAXWS25PEYEMGONWFI
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

oauth2:
  user:
    google:
      client-id: 737164190018-n4pfqlkmbkg6faijmof10ek07alp7utj.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://luckyseven-env.ap-northeast-2.elasticbeanstalk.com/oauth/google/callback
    naver:
      client-id: W3Flx3FAW3HXvuFho44N
      client-secret: tvAp_HdFmG
      redirect-uri: "http://luckyseven-env.ap-northeast-2.elasticbeanstalk.com/oauth/naver/callback"
      authorization_grant_type: authorization_code
      scope: name,email,profile_image
      client-name: Naver
  provider:
    google:
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
    naver:
      authorization_uri: https://nid.naver.com/oauth2.0/authorize
      token_uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
      user_name_attribute: response

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400 # 24시간


