server:
  port: 8080

spring:
  config:
    import:
      - optional:classpath:/application.yml
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/test;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: 'true'
  jpa:
    defer-datasource-initialization: true