server:
  port: 8080

spring:
  config:
    import:
      - optional:classpath:/application.yml
  h2:
    console:
      enabled: 'true'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8000/luckyseven
    username: jimin
    password: simon1126
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 46ec58d196bd0e72f56e34641ceec564
            redirect-uri: http://localhost:3000/auth/kakao
            client-authentication-method: POST
            client-secret: dHp9KmlsjhGhVpE6mFA8jXfsYF1HRzTV
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - birthday
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

oauth2:
  user:
    google:
      client-id: 737164190018-n4pfqlkmbkg6faijmof10ek07alp7utj.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://localhost:8080/oauth/google/callback
    naver:
      client-id: W3Flx3FAW3HXvuFho44N
      client-secret: tvAp_HdFmG
      redirect-uri: "http://localhost:8080/oauth/naver/callback"
      authorization_grant_type: authorization_code
      scope: name,email,profile_image
      client-name: Naver
  provider:
    google:
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
    naver:
      authorization_uri: https://nid.naver.com/oauth2.0/authorize
      token_uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
      user_name_attribute: response